server:
  #https监听端口
  port: 9080
  custom:
    #http监听端口
    httpPort: 9080
  ssl:
    key-store: classpath:3430736_www.moxiang.online.jks
    key-store-password: vB7hjyel
    key-store-type: JKS
    key-alias: moXiangSSL

#Spring配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.77.182.31:3306/newxiaoa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
